name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup Environment
      run:
         echo Entering "$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")" in `pwd`
         set -e
         export JAVA_HOME=${JAVA_HOME:-$(dirname $(dirname $(readlink -f $(which javac))))}
         git -C /tmp clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
         export JSR308="${JSR308:-$(cd .. && pwd -P)}"
         export CHECKERFRAMEWORK="${CHECKERFRAMEWORK:-$(pwd -P)/../checker-framework}"
         export PATH=$AFU/scripts:$JAVA_HOME/bin:$PATH
    - name: Build Checker Framework
      run:
        /tmp/plume-scripts/git-clone-related eisop checker-framework ${CHECKERFRAMEWORK}
        cd $CHECKERFRAMEWORK && checker/bin-devel/build.sh downloadjdk
    - name: ./gradlew -PcfLocal build
      run: ./gradlew -PcfLocal build
    - name: ./gradlew requireJavadoc
      run: ./gradlew requireJavadoc
    - name: ./gradlew spotlessCheck
      run: ./gradlew spotlessCheck
