name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: ./gradlew --console=plain -PcfLocal compileJava compileTestJava
      run: ./gradlew --console=plain -PcfLocal compileJava compileTestJava
    - name: ./gradlew build
      run: ./gradlew build
    - name: ./gradlew requireJavadoc
      run: ./gradlew requireJavadoc
    - name: ./gradlew spotlessCheck
      run: ./gradlew spotlessCheck
