name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup Environment
      run: |
        chmod +x ./.setup-CF.sh
        ./.setup-CF.sh
    - name: ./gradlew -PcfLocal build
      run: ./gradlew -PcfLocal build
    - name: ./gradlew requireJavadoc
      run: ./gradlew requireJavadoc
    - name: ./gradlew spotlessCheck
      run: ./gradlew spotlessCheck
